/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/buX6zAWScAr
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { Button } from "@/components/ui/button"
import axios from "axios"
import { useRouter } from "next/router"
import { FormEvent, useState } from "react"
import toast from "react-hot-toast"

export default function Login() {
  const router = useRouter()
    const [email, setEmail] = useState('')
    const  [password, setPassword] = useState('')
    
    const loginHandler = async (e: FormEvent) => {
        e.preventDefault()
        try {
            let req = await axios.post('/api/auth/loginHandler', {
                data: {
                    email,
                    password
                }
               })
               
                toast.success(`Sucessfully Logged In!`)
                return router.push('/')
        } catch(e) {
           return toast.error(`Incorrect Login Information`)
        }
           
    }
  return (
    <div className="min-h-screen bg-gray-900 py-6 flex flex-col justify-center sm:py-12">
      <div className="relative py-3 sm:max-w-xl sm:mx-auto">
        <div className="absolute inset-0 bg-gradient-to-r from-blue-900 to-indigo-900 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl" />
        <div className="relative px-4 py-10 bg-gray-800 shadow-lg sm:rounded-3xl sm:p-20">
          <div className="max-w-md mx-auto">
            <div>
              <img className="h-7 sm:h-8" src="/placeholder.svg" />
            </div>
            <div className="divide-y divide-gray-700">
              <form>

              <div className="py-8 text-base leading-6 space-y-4 text-gray-300 sm:text-lg sm:leading-7">
                <div className="relative">
                  <Label  className="leading-7 text-sm text-gray-400" htmlFor="email">
                    Email
                  </Label>
                  <Input onChange={(e) => setEmail(e.target.value)} className="mt-1 block w-full bg-gray-700 text-white" id="username" type="text" />
                </div>
                <div className="relative">
                  <Label className="leading-7 text-sm text-gray-400" htmlFor="password">
                    Password
                  </Label>
                  <Input onChange={(e) => setPassword(e.target.value)} className="mt-1 block w-full bg-gray-700 text-white" id="password" type="password" />
                </div>
                <div className="flex items-center justify-between">
                  <div>
                    <Link className="text-sm text-gray-500 underline" href="#">
                      Forgot your password?
                    </Link>
                  </div>
                </div>
                <Button
                  type="submit"
                  onClick={(e) => loginHandler(e)}
                  
                  className="w-full py-2 px-4 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-gray-700 hover:bg-gray-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
                >
                  Login
                </Button>
              </div>
              <div className="pt-6 text-base leading-6 font-bold sm:text-lg sm:leading-7">
                <p className="text-gray-300">Don't have an account?</p>
                <Link className="text-blue-400 hover:text-blue-300" href="/auth/signup">
                  {" "}
                  Sign up
                </Link>
              </div>
              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
